# Generated by Django 5.0.3 on 2024-04-13 11:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_chat_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
